print("Qual o sistema será usado: (1=simples,2=atrito,3=amortecimento,4=nao-linear) \n ")
x = readline()
if x == "1"
    print("Escreva as constantes: \n")
    print("Massa 1: \n")
    m₁ = readline()
    m₁ = parse(Float64, m₁)
    print("Massa 2: \n")
    m₂ = readline()
    m₂ = parse(Float64, m₂)
    print("Constante da mola 1: \n")
    k₁ = readline()
    k₁ = parse(Float64, k₁)
    print("Constante da mola 2: \n")
    k₂ = readline()
    k₂ = parse(Float64, k₂)
    print("Comprimento de relaxamento 1: \n")
    r₁ = readline()
    r₁ = parse(Float64, r₁)
    print("Comprimento de relaxamento 2: \n")
    r₂ = readline()
    r₂ = parse(Float64, r₂)
    print("Velocidade inicial 1: \n")
    v₀₁ = readline()
    v₀₁ = parse(Float64, v₀₁)
    print("Velocidade inicial 2: \n")
    v₀₂ = readline()
    v₀₂ = parse(Float64, v₀₂)
    print("Posição inicial 1: \n")
    x₀₁ = readline()
    x₀₁ = parse(Float64, x₀₁)
    print("Posição inicial 2: \n")
    x₀₂ = readline()
    x₀₂ = parse(Float64, x₀₂)
    print("Variação do tempo: \n")
    tf = readline()
    tf = parse(Float64, tf)
    print("Numero de interações: \n")
    N = readline()
    N = parse(Int64, N)
    include("Double-Spring-Simple.jl")
    print("Escolha, grafico ou animação? (1=grafico,2=animação) \n")
    y = readline()
    if y == "1"
        print("Escolha, deslocamentoXtempo ou deslocamentoXdeslocamento? (1=dXt,2=dXd) \n")
        z = readline()
        if z == "1"
            include("Graph-Motion-by-Time.jl")
        elseif z == "2"
            include("Graph-Motion-by-Motion.jl")
        end
    elseif y == "2" 
        include("Gif-Double-Spring.jl")
    end
elseif x == "2"
    print("Escreva as constantes: \n")
    print("Massa 1: \n")
    m₁ = readline()
    m₁ = parse(Float64, m₁)
    print("Massa 2: \n")
    m₂ = readline()
    m₂ = parse(Float64, m₂)
    print("Constante da mola 1: \n")
    k₁ = readline()
    k₁ = parse(Float64, k₁)
    print("Constante da mola 2: \n")
    k₂ = readline()
    k₂ = parse(Float64, k₂)
    print("Constante de atrito 1: \n")
    μ₁ = readline()
    μ₁ = parse(Float64, μ₁)
    print("Constante de atrito 2: \n")
    μ₂ = readline()
    μ₂ = parse(Float64, μ₂)
    print("Comprimento de relaxamento 1: \n")
    r₁ = readline()
    r₁ = parse(Float64, r₁)
    print("Comprimento de relaxamento 2: \n")
    r₂ = readline()
    r₂ = parse(Float64, r₂)
    print("Velocidade inicial 1: \n")
    v₀₁ = readline()
    v₀₁ = parse(Float64, v₀₁)
    print("Velocidade inicial 2: \n")
    v₀₂ = readline()
    v₀₂ = parse(Float64, v₀₂)
    print("Posição inicial 1: \n")
    x₀₁ = readline()
    x₀₁ = parse(Float64, x₀₁)
    print("Posição inicial 2: \n")
    x₀₂ = readline()
    x₀₂ = parse(Float64, x₀₂)
    print("Variação do tempo: \n")
    tf = readline()
    tf = parse(Float64, tf)
    print("Numero de interações: \n")
    N = readline()
    N = parse(Int64, N)
    include("Double-Spring-Friction.jl")
    print("Escolha, grafico ou animação? (1=grafico,2=animação) \n")
    y = readline()
    if y == "1"
        print("Escolha, deslocamentoXtempo ou deslocamentoXdeslocamento? (1=dXt,2=dXd) \n")
        z = readline()
        if z == "1"
            include("Graph-Motion-by-Time.jl")
        elseif z == "2"
            include("Graph-Motion-by-Motion.jl")
        end
    elseif y == "2" 
        include("Gif-Double-Spring.jl")
    end
elseif x == "3"
    print("Escreva as constantes: \n")
    print("Massa 1: \n")
    m₁ = readline()
    m₁ = parse(Float64, m₁)
    print("Massa 2: \n")
    m₂ = readline()
    m₂ = parse(Float64, m₂)
    print("Constante da mola 1: \n")
    k₁ = readline()
    k₁ = parse(Float64, k₁)
    print("Constante da mola 2: \n")
    k₂ = readline()
    k₂ = parse(Float64, k₂)
    print("Constante de amortecimento 1: \n")
    δ₁ = readline()
    δ₁ = parse(Float64, δ₁)
    print("Constante de amortecimento 2: \n")
    δ₂ = readline()
    δ₂ = parse(Float64, δ₂)
    print("Comprimento de relaxamento 1: \n")
    r₁ = readline()
    r₁ = parse(Float64, r₁)
    print("Comprimento de relaxamento 2: \n")
    r₂ = readline()
    r₂ = parse(Float64, r₂)
    print("Velocidade inicial 1: \n")
    v₀₁ = readline()
    v₀₁ = parse(Float64, v₀₁)
    print("Velocidade inicial 2: \n")
    v₀₂ = readline()
    v₀₂ = parse(Float64, v₀₂)
    print("Posição inicial 1: \n")
    x₀₁ = readline()
    x₀₁ = parse(Float64, x₀₁)
    print("Posição inicial 2: \n")
    x₀₂ = readline()
    x₀₂ = parse(Float64, x₀₂)
    print("Variação do tempo: \n")
    tf = readline()
    tf = parse(Float64, tf)
    print("Numero de interações: \n")
    N = readline()
    N = parse(Int64, N)
    include("Double-Spring-Damping.jl")
    print("Escolha, grafico ou animação? (1=grafico,2=animação) \n")
    y = readline()
    if y == "1"
        print("Escolha, deslocamentoXtempo ou deslocamentoXdeslocamento? (1=dXt,2=dXd) \n")
        z = readline()
        if z == "1"
            include("Graph-Motion-by-Time.jl")
        elseif z == "2"
            include("Graph-Motion-by-Motion.jl")
        end
    elseif y == "2" 
        include("Gif-Double-Spring.jl")
    end
elseif x == "4"
    print("Escreva as constantes: \n")
    print("Massa 1: \n")
    m₁ = readline()
    m₁ = parse(Float64, m₁)
    print("Massa 2: \n")
    m₂ = readline()
    m₂ = parse(Float64, m₂)
    print("Constante da mola 1: \n")
    k₁ = readline()
    k₁ = parse(Float64, k₁)
    print("Constante da mola 2: \n")
    k₂ = readline()
    k₂ = parse(Float64, k₂)
    print("Constante de não linearidade 1: \n")
    μ₁ = readline()
    μ₁ = parse(Float64, μ₁)
    print("Constante de não linearidade 2: \n")
    μ₂ = readline()
    μ₂ = parse(Float64, μ₂)
    print("Existe amortecimento? (0=não,1=sim) \n")
    w = readline()
    if w == "0"
        δ₁, δ₂ = 0.0, 0.0
    elseif w == "1"
        print("Constante de amortecimento 1: \n")
        δ₁ = readline()
        δ₁ = parse(Float64, δ₁)
        print("Constante de amortecimento 2: \n")
        δ₂ = readline()
        δ₂ = parse(Float64, δ₂)
    end
    print("Comprimento de relaxamento 1: \n")
    r₁ = readline()
    r₁ = parse(Float64, r₁)
    print("Comprimento de relaxamento 2: \n")
    r₂ = readline()
    r₂ = parse(Float64, r₂)
    print("Velocidade inicial 1: \n")
    v₀₁ = readline()
    v₀₁ = parse(Float64, v₀₁)
    print("Velocidade inicial 2: \n")
    v₀₂ = readline()
    v₀₂ = parse(Float64, v₀₂)
    print("Posição inicial 1: \n")
    x₀₁ = readline()
    x₀₁ = parse(Float64, x₀₁)
    print("Posição inicial 2: \n")
    x₀₂ = readline()
    x₀₂ = parse(Float64, x₀₂)
    print("Variação do tempo: \n")
    tf = readline()
    tf = parse(Float64, tf)
    print("Numero de interações: \n")
    N = readline()
    N = parse(Int64, N)
    include("Double-Spring-Non-Linear.jl")
    print("Escolha, grafico ou animação? (1=grafico,2=animação) \n")
    y = readline()
    if y == "1"
        print("Escolha, deslocamentoXtempo ou deslocamentoXdeslocamento? (1=dXt,2=dXd) \n")
        z = readline()
        if z == "1"
            include("Graph-Motion-by-Time.jl")
        elseif z == "2"
            include("Graph-Motion-by-Motion.jl")
        end
    elseif y == "2" 
        include("Gif-Double-Spring.jl")
    end
end
